server:
  port: 9001
spring:
  application:
    name: kotlin-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/whl?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource